// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vthjgdhcmmusupfdwglq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ0aGpnZGhjbW11c3VwZmR3Z2xxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxNTY5MjMsImV4cCI6MjA3MDczMjkyM30.awCMDdcH9d-2D4Q7LKGGC2TLDIqT530yXt5GNIcbCbM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});